#!/usr/bin/env python3
"""Round 3A QA/provenance handoff for Strategy A Ib len255 outputs."""

from __future__ import annotations

import argparse
import csv
import hashlib
import subprocess
from pathlib import Path

from target_representation_audit import parse_cdhit_clusters, read_qc


GENERATED_ARTIFACTS = [
    (
        "results/02_qc_len255/qc_classification_Ib.tsv",
        "formal_len255_ib_qc_table",
        True,
        "python scripts/qc_length_coverage.py --fasta results/01_mining/hits_Ib_clean.fasta --domtbl results/01_mining/hits_Ib.domtbl --hmm_length 334 --subtype Ib --canonical_min 255 --canonical_max 450 --cov_min 0.70 --outdir results/02_qc_len255",
        "Tracked Round 2 formal Ib len255 QC table.",
    ),
    (
        "results/02_qc_len255/qc_pass_Ib.fasta",
        "formal_len255_ib_pass_fasta",
        False,
        "python scripts/qc_length_coverage.py --fasta results/01_mining/hits_Ib_clean.fasta --domtbl results/01_mining/hits_Ib.domtbl --hmm_length 334 --subtype Ib --canonical_min 255 --canonical_max 450 --cov_min 0.70 --outdir results/02_qc_len255",
        "Ignored FASTA generated by formal Ib len255 QC.",
    ),
    (
        "results/02_qc_len255/qc_long_Ib.fasta",
        "formal_len255_ib_long_fasta",
        False,
        "python scripts/qc_length_coverage.py --fasta results/01_mining/hits_Ib_clean.fasta --domtbl results/01_mining/hits_Ib.domtbl --hmm_length 334 --subtype Ib --canonical_min 255 --canonical_max 450 --cov_min 0.70 --outdir results/02_qc_len255",
        "Ignored FASTA generated by formal Ib len255 QC.",
    ),
    (
        "results/02_qc_len255/fragments_Ib.fasta",
        "formal_len255_ib_fragment_fasta",
        False,
        "python scripts/qc_length_coverage.py --fasta results/01_mining/hits_Ib_clean.fasta --domtbl results/01_mining/hits_Ib.domtbl --hmm_length 334 --subtype Ib --canonical_min 255 --canonical_max 450 --cov_min 0.70 --outdir results/02_qc_len255",
        "Ignored FASTA generated by formal Ib len255 QC.",
    ),
    (
        "results/02_qc_len255/Ib_len255_pass_plus_long.fasta",
        "formal_len255_ib_cdhit_input",
        False,
        "cat results/02_qc_len255/qc_pass_Ib.fasta results/02_qc_len255/qc_long_Ib.fasta > results/02_qc_len255/Ib_len255_pass_plus_long.fasta",
        "Ignored FASTA created by concatenating len255 PASS_CANONICAL and PASS_LONG records.",
    ),
    (
        "results/02_qc_len255/nr80_Ib.fasta",
        "formal_len255_ib_nr80_representatives",
        True,
        "conda run -n dah7ps_v4 cd-hit -i results/02_qc_len255/Ib_len255_pass_plus_long.fasta -o results/02_qc_len255/nr80_Ib.fasta -c 0.80 -n 5 -M 4000 -T 20 -d 0 -p 1",
        "Ignored FASTA required for Round 3B nr80_all construction.",
    ),
    (
        "results/02_qc_len255/nr80_Ib.fasta.clstr",
        "formal_len255_ib_nr80_clusters",
        True,
        "conda run -n dah7ps_v4 cd-hit -i results/02_qc_len255/Ib_len255_pass_plus_long.fasta -o results/02_qc_len255/nr80_Ib.fasta -c 0.80 -n 5 -M 4000 -T 20 -d 0 -p 1",
        "Ignored CLSTR required for Round 3B target representation checks.",
    ),
    (
        "results/02_qc_len255/seeds60_Ib.fasta",
        "formal_len255_ib_seeds60_representatives",
        False,
        "conda run -n dah7ps_v4 cd-hit -i results/02_qc_len255/nr80_Ib.fasta -o results/02_qc_len255/seeds60_Ib.fasta -c 0.60 -n 4 -M 4000 -T 20 -d 0 -p 1",
        "Ignored FASTA; diversity-panel context only, not final-tree tip presence.",
    ),
    (
        "results/02_qc_len255/seeds60_Ib.fasta.clstr",
        "formal_len255_ib_seeds60_clusters",
        False,
        "conda run -n dah7ps_v4 cd-hit -i results/02_qc_len255/nr80_Ib.fasta -o results/02_qc_len255/seeds60_Ib.fasta -c 0.60 -n 4 -M 4000 -T 20 -d 0 -p 1",
        "Ignored CLSTR; diversity-panel context only, not final-tree tip presence.",
    ),
]

ACCEPTABILITY_TARGETS = [
    ("PfuDAH7PS", "UniRef90_Q8U0A9"),
    ("ApeDAH7PS", "UniRef90_Q9YEJ7"),
    ("PniDAH7PS", "UniRef90_F9DH16"),
    ("legacy A0A0F2JEB6", ""),
]

FLAGGED_RESCUES = [
    ("KDOPS-like", "UniRef90_A0A5E4LPI9"),
    ("hypothetical/uncharacterized", "UniRef90_UPI00345644EC"),
    ("hypothetical/uncharacterized", "UniRef90_UPI0026F16738"),
    ("hypothetical/uncharacterized", "UniRef90_UPI003593E582"),
    ("other/ambiguous", "UniRef90_A0A0E3W3M4"),
    ("other/ambiguous", "UniRef90_A0A645BIV5"),
]


def run_git(root: Path, *args: str) -> bool:
    return subprocess.run(
        ["git", *args],
        cwd=root,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    ).returncode == 0


def md5(path: Path) -> str:
    digest = hashlib.md5()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_fasta(path: Path) -> dict[str, dict[str, str]]:
    records: dict[str, dict[str, str]] = {}
    if not path.exists():
        return records
    current_id = ""
    current_header = ""
    seq_parts: list[str] = []

    def flush() -> None:
        if current_id:
            records[current_id] = {
                "header": current_header,
                "sequence": "".join(seq_parts),
                "length": str(len("".join(seq_parts))),
            }

    with path.open() as handle:
        for line in handle:
            if line.startswith(">"):
                flush()
                current_header = line[1:].strip()
                current_id = current_header.split()[0]
                seq_parts = []
            else:
                seq_parts.append(line.strip())
    flush()
    return records


def header_annotation(header: str) -> str:
    if not header:
        return ""
    body = header.split(" ", 1)[1] if " " in header else ""
    return body.split(" n=", 1)[0]


def header_taxonomy(header: str) -> str:
    if "Tax=" not in header:
        return ""
    text = header.split("Tax=", 1)[1]
    return text.split(" TaxID=", 1)[0]


def qc_length(row: dict[str, str] | None) -> str:
    if not row:
        return ""
    return row.get("L_seq", "")


def qc_cov(row: dict[str, str] | None) -> str:
    if not row:
        return ""
    return row.get("cov_best", row.get("cov_hmm", ""))


def write_generated_manifest(root: Path) -> None:
    out_path = root / "results/02_qc_len255/generated_artifacts_manifest.tsv"
    columns = [
        "relative_path",
        "artifact_role",
        "file_size_bytes",
        "md5",
        "tracked_by_git",
        "ignored_by_git",
        "required_for_next_stage",
        "recreate_command_or_source",
        "notes",
    ]
    with out_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, delimiter="\t", fieldnames=columns)
        writer.writeheader()
        for rel_path, role, required, recreate, notes in GENERATED_ARTIFACTS:
            path = root / rel_path
            tracked = run_git(root, "ls-files", "--error-unmatch", rel_path)
            ignored = run_git(root, "check-ignore", "-q", rel_path)
            writer.writerow(
                {
                    "relative_path": rel_path,
                    "artifact_role": role,
                    "file_size_bytes": str(path.stat().st_size) if path.exists() else "",
                    "md5": md5(path) if path.exists() else "",
                    "tracked_by_git": str(tracked).lower(),
                    "ignored_by_git": str(ignored).lower(),
                    "required_for_next_stage": str(required).lower(),
                    "recreate_command_or_source": recreate,
                    "notes": notes if path.exists() else f"MISSING: {notes}",
                }
            )


def read_target_rows(root: Path) -> dict[str, dict[str, str]]:
    with (root / "results/02_qc_len255/target_representation.tsv").open(newline="") as handle:
        return {
            row["abbrev"]: row
            for row in csv.DictReader(handle, delimiter="\t")
        }


def write_acceptability(root: Path) -> None:
    target_rows = read_target_rows(root)
    qc = read_qc(root / "results/02_qc_len255/qc_classification_Ib.tsv")
    input_records = read_fasta(root / "results/01_mining/hits_Ib_clean.fasta")
    nr80_records = read_fasta(root / "results/02_qc_len255/nr80_Ib.fasta")
    columns = [
        "target",
        "target_id",
        "target_length",
        "target_len255_qc_status",
        "nr80_status",
        "nr80_representative",
        "identity_if_absorbed",
        "target_local_coverage",
        "representative_length",
        "representative_hmm_coverage",
        "representative_taxonomy",
        "representative_annotation",
        "acceptability_call",
        "curation_call",
        "label_policy",
        "notes",
    ]
    out_path = root / "results/02_qc_len255/representative_acceptability_round3A.tsv"
    with out_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, delimiter="\t", fieldnames=columns)
        writer.writeheader()
        for target, target_id in ACCEPTABILITY_TARGETS:
            target_row = target_rows[target]
            if target == "legacy A0A0F2JEB6":
                writer.writerow(
                    {
                        "target": target,
                        "target_id": target_row["primary_accession"],
                        "target_length": "",
                        "target_len255_qc_status": "unresolved_accession",
                        "nr80_status": "unresolved_accession",
                        "nr80_representative": "",
                        "identity_if_absorbed": "",
                        "target_local_coverage": "",
                        "representative_length": "",
                        "representative_hmm_coverage": "",
                        "representative_taxonomy": "",
                        "representative_annotation": "",
                        "acceptability_call": "unresolved_accession",
                        "curation_call": "unresolved_legacy_accession",
                        "label_policy": target_row["label_policy"],
                        "notes": "Do not merge silently with V8CS59 / UniRef90_F9DH16.",
                    }
                )
                continue

            rep_id = target_row["nr80_representative"]
            rep_qc = qc.get(rep_id)
            rep_record = nr80_records.get(rep_id, input_records.get(rep_id, {}))
            if target == "PfuDAH7PS":
                acceptability = "acceptable_nr80_surrogate"
                curation = "accepted_surrogate"
                notes = "Formal nr80 confirms UniRef90_UPI0002AF51CE at 95.04% identity."
            elif target == "ApeDAH7PS":
                acceptability = "direct_nr80_tip"
                curation = "direct_tip_accepted"
                notes = "Formal nr80 confirms Q9YEJ7 is the representative."
            else:
                acceptability = "needs_curation"
                curation = "needs_curation"
                notes = (
                    "Formal nr80 confirms surrogate representation, but identity is 81.92%; "
                    "review representative taxonomy/annotation before final labeling."
                )
            writer.writerow(
                {
                    "target": target,
                    "target_id": target_id,
                    "target_length": target_row["length"],
                    "target_len255_qc_status": target_row["len255_qc_status"],
                    "nr80_status": target_row["nr80_status"],
                    "nr80_representative": rep_id,
                    "identity_if_absorbed": target_row["nr80_identity_if_absorbed"],
                    "target_local_coverage": target_row["nr80_local_target_coverage"],
                    "representative_length": qc_length(rep_qc) or rep_record.get("length", ""),
                    "representative_hmm_coverage": qc_cov(rep_qc),
                    "representative_taxonomy": header_taxonomy(rep_record.get("header", "")),
                    "representative_annotation": header_annotation(rep_record.get("header", "")),
                    "acceptability_call": acceptability,
                    "curation_call": curation,
                    "label_policy": target_row["label_policy"],
                    "notes": notes,
                }
            )


def write_flagged_adjudication(root: Path) -> None:
    qc = read_qc(root / "results/02_qc_len255/qc_classification_Ib.tsv")
    input_records = read_fasta(root / "results/01_mining/hits_Ib_clean.fasta")
    nr80_hits = parse_cdhit_clusters(root / "results/02_qc_len255/nr80_Ib.fasta.clstr")
    columns = [
        "flag_class",
        "seq_id",
        "length",
        "cov_best",
        "annotation_or_header",
        "nr80_status",
        "nr80_representative",
        "identity_if_absorbed",
        "recommended_action",
        "notes",
    ]
    out_path = root / "results/02_qc_len255/len255_flagged_rescue_adjudication.tsv"
    with out_path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, delimiter="\t", fieldnames=columns)
        writer.writeheader()
        for flag_class, seq_id in FLAGGED_RESCUES:
            row = qc.get(seq_id, {})
            hit = nr80_hits.get(seq_id)
            if hit is None:
                nr80_status = "absent_after_nr80"
                rep = ""
                identity = ""
            elif hit.is_representative:
                nr80_status = "direct_nr80_representative"
                rep = hit.representative
                identity = ""
            else:
                nr80_status = "absorbed_by_nr80_surrogate"
                rep = hit.representative
                identity = hit.identity
            if flag_class == "KDOPS-like":
                action = "manual_review_before_final_tree"
            elif flag_class == "hypothetical/uncharacterized":
                action = "manual_review_before_final_tree"
            else:
                action = "needs_annotation_check"
            writer.writerow(
                {
                    "flag_class": flag_class,
                    "seq_id": seq_id,
                    "length": row.get("L_seq", ""),
                    "cov_best": qc_cov(row),
                    "annotation_or_header": input_records.get(seq_id, {}).get("header", ""),
                    "nr80_status": nr80_status,
                    "nr80_representative": rep,
                    "identity_if_absorbed": identity,
                    "recommended_action": action,
                    "notes": "Flag only; no sequence removed in Round 3A.",
                }
            )


def write_handoff(root: Path) -> None:
    text = """# Strategy A Round 3A downstream handoff

## Formal Ib replacement files

- Use `results/02_qc_len255/nr80_Ib.fasta` instead of `results/02_qc/nr80_Ib.fasta` for any Round 3B `nr80_all` construction.
- Use `results/02_qc_len255/nr80_Ib.fasta.clstr` for target/surrogate checks.
- Keep `results/02_qc_len255/qc_classification_Ib.tsv` as the formal len255 Ib QC provenance table.

## Ia/II reference files

- Keep the current staged Ia/II references for Round 3B unless a later task explicitly reruns them:
  `results/02_qc/nr80_Ia.fasta`, `results/02_qc/nr80_Ia.fasta.clstr`,
  `results/02_qc/nr80_II.fasta`, and `results/02_qc/nr80_II.fasta.clstr`.
- The staged Ia/II files are reference artifacts copied from the authorized source worktree and recorded in `results/02_qc_len255/input_staging_manifest.tsv`.

## Ignored but required next-stage artifacts

- Required ignored artifacts: `results/02_qc_len255/nr80_Ib.fasta` and `results/02_qc_len255/nr80_Ib.fasta.clstr`.
- Required tracked artifact: `results/02_qc_len255/qc_classification_Ib.tsv`.
- MD5/file-size provenance is recorded in `results/02_qc_len255/generated_artifacts_manifest.tsv`.

## Round 3B nr80_all command

Do not overwrite legacy `results/02_qc/nr80_all` paths. Use a versioned len255 path:

```bash
cat \\
  results/02_qc/nr80_Ia.fasta \\
  results/02_qc_len255/nr80_Ib.fasta \\
  results/02_qc/nr80_II.fasta \\
  > results/02_qc_len255/nr80_all_len255.fasta
```

Then record sequence count and md5 for `results/02_qc_len255/nr80_all_len255.fasta` before any core extraction.

## Round 3B representation checks

- `Q8U0A9` should not be expected as a direct nr80 tip; check that `UniRef90_UPI0002AF51CE` is present in the len255 `nr80_all` output.
- `Q9YEJ7` should be present as `UniRef90_Q9YEJ7`.
- `V8CS59` / `UniRef90_F9DH16` should not be treated as resolved by exact tip; check that surrogate `UniRef90_A0A379DXQ3` is present and keep Pni labeling under curation.

Suggested checks after Round 3B builds `nr80_all_len255.fasta`:

```bash
rg -n '^>UniRef90_UPI0002AF51CE\\b|^>UniRef90_Q9YEJ7\\b|^>UniRef90_A0A379DXQ3\\b' results/02_qc_len255/nr80_all_len255.fasta
rg -n '^>UniRef90_Q8U0A9\\b|^>UniRef90_F9DH16\\b|^>A0A0F2JEB6\\b' results/02_qc_len255/nr80_all_len255.fasta
```

## HOLD status

- `noO66496 formal S1` remains HOLD.
- `S2 noO66496` remains HOLD.
- QC3/root stability remains HOLD.
- Root-sensitive ASR remains HOLD.

## Claims not allowed

- Do not claim rooting solved.
- Do not claim QC3 released.
- Do not claim ASR released.
- Do not claim all targets are direct tips.
- Do not introduce forced-retain policy or change CD-HIT thresholds.
"""
    (root / "results/02_qc_len255/round3A_downstream_handoff.md").write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Project root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    write_generated_manifest(root)
    write_acceptability(root)
    write_flagged_adjudication(root)
    write_handoff(root)


if __name__ == "__main__":
    main()
